export const CoordLetter = {
  text: "We are Iris Rivera, Banesa Valencia, and Sawyer Rudy, collectively known as Team I.B.S, and we are your 2026 DINO-Week Coordinators!\n\n As O-Week Coordinators, it’s our job to make sure that your hatching into college goes as smoothly as it possibly can, and that all of you incoming Jonesians are given the best opportunity to dino-soar. In just a week, we will introduce you to the many resources at Jones and Rice that are established to ensure that each and every one of you has the tools to succeed and leave your claw-prints on our community. We know it can be scary; we were in your shoes less than 2 years ago, but it is not veloci-rapture. We will be here to support you every step of the way. Rice's Orientation-Week, otherwise known as “O-Week”, is unique and distinguished from orientation programs at other universities. Broadly, events in O-Week can be divided into three ways: events that help you plan your classes and prepare for them, events that describe the resources you have at Rice and beyond, and events that help you get to know the family of Jones and of Rice! And if you’re worried about bringing anything or being prepared for any of this, don’t worry – this book, and the people around you during this exciting week, will help you to know exactly what to bring, and what to expect at any given moment. It’s okay if you don’t have everything figured out right now—what classes to take, what clubs to join, or where you want to end up after graduation. As your Coords and part of your O-Week Team, we’ll guide your tracks through the Mesozoic jungle of college. \n\n The very first people you’ll meet during O-Week will be your Advisors, a hand-picked, diverse, engaged, and trained group of upperclassmen who volunteer part of their summer to learn how to best introduce you to Jones. Every freshman is paired with 4-5 Advisors and 8-10 other freshmen, who all together form an “O-Week Family”. This group is not only a major part of your O-Week, but also your whole first year – you’ll check in on each other, share meals weekly, and find the answers to any questions you may have. As the saying here at Rice goes, O-Week is forever.\n\n All throughout your new nest at Jones, you will encounter every species of dinosaur, with each bringing its own set of strengths and shortcomings. Despite these variations, you will find that any and every one of your fellow Jonesians will always be there to protect their hatch. It is for this reason that we chose DinO-Week to be our Jones O-Week 2026 Theme. No two people hatch into Jones the same; some of our hatchlings may fly, some may swim, some may have feathers, and some may have spikes, but we are undeniably exuberant to welcome all regardless. College will undeniably send some meteors in your direction, but fret not, we will be there to support every step of the way. \n\n You probably have a lot of questions going into O-Week, but never fear. No matter what happens, the three of us and the rest of your nest will always be here to help. Don’t be afraid to reach out with any concerns. \n\n We can’t wait to welcome you with open arms!",
  coordInfo: [
    {
      name: "Iris Rivera",
      phone: "ir32@rice.edu",
    },
    {
      name: "Banesa Valencia ",
      phone: "bv23@rice.edu",
    },
    {
      name: "Sawyer Rudy",
      phone: "sr168@rice.edu",
    },
  ],
  email: "marygibbsjonesoweek@gmail.com",
};

export const CoordBios = [
  {
    name: "IRIS RIVERA",
    bio: "Iris is a junior from Austin, TX studying Psychology. Outside of academics, she loves listening to music, taking walks, thrifting, frequenting the Jitchen late at night, and rotting on TikTok. ",
    img: "./images/oweek/coords/Iris.JPG",
  },
  {
    name: "BANESA VALENCIA",
    bio: "Banesa is a junior from Ridgeland, Ms studying Mathematics and English on the Creative writing track. She is known for her insane sudoku stats, making friendship bracelets in the 1N lobby, and working at the RMC info desk.",
    img: "./images/oweek/coords/Banesa.JPG",
  },
  {
    name: "SAWYER RUDY",
    bio: "Sawyer is a Sophmore from Chandler, Arizona studying Chemical Engineering with aspirations of going to medical school. He is known for working various jobs in the RMC, frequenting the North laundry room and 3N table, and bringing an overall sense of whimsy.",
    img: "./images/oweek/coords/Sawyer.JPG",
  },
];
export const OWeekGroups = [
  {
    name: "Star Wars: Attack of the Jones",
    members: "Jaemason Long, Nancy Martinez, Evan Ringwald, Milène Hacheme",
    img: "./images/oweek/oweek-groups/starwars/starwars.jpg",
    profiles: [
      {
        name: "JAEMASON L",
        email: "jll16@rice.edu",
        major: "Business and Political Science",
        collegetag: "./college-tags/lovett_tag.png",
        img: "./images/oweek/oweek-groups/starwars/jaemason.jpg",
      },
      {
        name: "NANCY M",
        email: "nm81@rice.edu",
        major: "Civil Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/starwars/nancy.jpg",
      },
      {
        name: "EVAN R",
        email: "er88@rice.edu",
        major: "Mechanical Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/starwars/evan.jpg",
      },
      {
        name: "MILÉNE H",
        email: "mh123@rice.edu",
        major: "Mechanical Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/starwars/milene.jpg",
      },
    ],
  },
  {
    name: "The Hubble Games: May the Stars be Ever in Your Favor",
    members: "Ismail Tambawala, Danielle Colon, Rachel Ayalon, Simon Quintero",
    img: "./images/oweek/oweek-groups/hubblegames/hubblegames.jpg",
    profiles: [
      {
        name: "ISMAIL T",
        email: "iat1@rice.edu",
        major: "Mechanical Engineering",
        collegetag: "./college-tags/willrice_tag.png",
        img: "./images/oweek/oweek-groups/hubblegames/ismi.jpg",
      },
      {
        name: "DANIELLE C",
        email: "dfc5@rice.edu",
        major: "Cognitive Sciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/hubblegames/danielle.jpg",
      },
      {
        name: "RACHEL A",
        email: "ra106@rice.edu",
        major: "Political Science and Social Policy Analysis",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/hubblegames/rachel_a.jpg",
      },
      {
        name: "SIMON Q",
        email: "spq1@rice.edu",
        major: "Economics and Finance",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/hubblegames/simon.jpg",
      },
    ],
  },
  {
    name: "Blank Space (Jones Version)",
    members: "Tim Voelker, Tori Barrera, Sawyer Rudy, Simmy Ghosh",
    img: "./images/oweek/oweek-groups/blankspace/blankspace.jpg",
    profiles: [
      {
        name: "TIM V",
        email: "tv30@rice.edu",
        major: "Political Science",
        collegetag: "./college-tags/duncan_tag.png",
        img: "./images/oweek/oweek-groups/blankspace/tim.jpg",
      },
      {
        name: "TORI B",
        email: "tb61@rice.edu",
        major: "Bioengineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/blankspace/tori.jpg",
      },
      {
        name: "SAWYER R",
        email: "sr168@rice.edu",
        major: "Physics",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/blankspace/sawyer.jpg",
      },
      {
        name: "SIMMY G",
        email: "sg256@rice.edu",
        major: "Managerial Economics and Organizational Sciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/blankspace/simmy.jpg",
      },
    ],
  },
  {
    name: "Mario Kart: Galaxy Road",
    members: "Faith Zhang, Justin Lopato, Ian Rodriguez, Katie Maurano",
    img: "./images/oweek/oweek-groups/mario/mario.jpg",
    profiles: [
      {
        name: "FAITH Z",
        email: "fz28@rice.edu",
        major: "Computer Science and Operations Research",
        collegetag: "./college-tags/weiss_tag.png",
        img: "./images/oweek/oweek-groups/mario/faith.jpg",
      },
      {
        name: "JUSTIN L",
        email: "ja130@rice.edu",
        major: "Computer Science",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/mario/justin.jpg",
      },
      {
        name: "IAN R",
        email: "ir33@rice.edu",
        major: "Political Science and Business",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/mario/ian.jpg",
      },
      {
        name: "KATIE M",
        email: "km78@rice.edu",
        major: "Psychology and Theater",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/mario/katie.jpg",
      },
    ],
  },
  {
    name: "Elton Jones: Rocketman",
    members: "Calvin Wong, Ava Brazell, Nina Yu, Alex Gonzalez, Grace Sattem",
    img: "./images/oweek/oweek-groups/rocketman/rocketman.jpg",
    profiles: [
      {
        name: "CALVIN W",
        email: "cw161@rice.edu",
        major: "Computer Science and Operations Research",
        collegetag: "./college-tags/lovett_tag.png",
        img: "./images/oweek/oweek-groups/rocketman/calvin.jpg",
      },
      {
        name: "AVA B",
        email: "amb36@rice.edu",
        major: "Political Science",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/rocketman/ava.jpg",
      },
      {
        name: "NINA Y",
        email: "ny21@rice.edu",
        major: "Health Sciences and Social Policy Analysis",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/rocketman/nina.jpg",
      },
      {
        name: "ALEX G",
        email: "aig1@rice.edu",
        major: "Biosciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/rocketman/alex.jpg",
      },
      {
        name: "GRACE S",
        email: "gcs2@rice.edu",
        major: "Psychology",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/rocketman/grace.jpg",
      },
    ],
  },
  {
    name: "Scooby-Doo and the Martian Crew",
    members: "Clay Goldsmith, Jessica Xu, Judson McGinnes, Varsha Chandramouli",
    img: "./images/oweek/oweek-groups/scoobydoo/scoobydoo.jpg",
    profiles: [
      {
        name: "CLAY G",
        email: "cg156@rice.edu",
        major: "Astrophysics",
        collegetag: "./college-tags/martel_tag.png",
        img: "./images/oweek/oweek-groups/scoobydoo/clay.jpg",
      },
      {
        name: "JESSICA X",
        email: "jwx2@rice.edu",
        major: "Enviornmental Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/scoobydoo/jessica.jpg",
      },
      {
        name: "JUDSON M",
        email: "jm323@rice.edu",
        major: "Mathmatical Economic Analysis and Operations Research",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/scoobydoo/jud.jpg",
      },
      {
        name: "VARSHA C",
        email: "vkc1@rice.edu",
        major: "Sports Medicine",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/scoobydoo/varsha.jpg",
      },
    ],
  },
  {
    name: "Spiderman: Into the Uni-verse",
    members: "Zoë Coleman, Sarah Choi, Eric Chen, Ayra Matondang",
    img: "./images/oweek/oweek-groups/spiderman/spiderman.jpg",
    profiles: [
      {
        name: "ZOË C",
        email: "zrc2@rice.edu",
        major: "Philosophy",
        collegetag: "./college-tags/wiess_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/zoe.jpg",
      },
      {
        name: "SARAH C",
        email: "sc258@rice.edu",
        major: "Chemistry",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/sarah.jpg",
      },
      {
        name: "ERIC C",
        email: "ec118@rice.edu",
        major: "Bioengineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/eric.jpg",
      },
      {
        name: "AYRA M",
        email: "asm20@rice.edu",
        major: "Social Policy Analysis and Cognitive Sciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/ayra.jpg",
      },
    ],
  },
  {
    name: "Despicable Meteor",
    members: "Jay Srivastava, Nihar Shetty, Banesa Valencia, Leela Sydow",
    img: "./images/oweek/oweek-groups/minions/minions.jpg",
    profiles: [
      {
        name: "JAY S",
        email: "js233@rice.edu",
        major: "Mechanical Engineering",
        collegetag: "./college-tags/hanszen_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/jay.jpg",
      },
      {
        name: "NIHAR S",
        email: "ns86@rice.edu",
        major: "Philosophy",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/nihar.jpg",
      },
      {
        name: "BANESA V",
        email: "bv23@rice.edu",
        major: "Chemical Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/banesa.jpg",
      },
      {
        name: "LEELA S",
        email: "lps6@rice.edu",
        major: "Sociology",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/spiderman/leela.jpg",
      },
    ],
  },
  {
    name: "Toy Starry: To Infinity and Beyond",
    members:
      "Audrey Arroyave, Ankhi Banerjee, Kenechukwi Okerke, Daniel Peinado",
    img: "./images/oweek/oweek-groups/toystarry/toystarry.jpg",
    profiles: [
      {
        name: "AUDREY A",
        email: "aga7@rice.edu",
        major: "Civil Engineering",
        collegetag: "./college-tags/lovett_tag.png",
        img: "./images/oweek/oweek-groups/toystarry/audrey.jpg",
      },
      {
        name: "ANKHI B",
        email: "ab235@rice.edu",
        major: "Computer Science",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/toystarry/ankhi.jpg",
      },
      {
        name: "KENECHUKWU OK",
        email: "ko27@rice.edu",
        major: "Computer Science",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/toystarry/kenechukwu.jpg",
      },
      {
        name: "DANIEL P",
        email: "drp5@rice.edu",
        major: "Spanish and Biosciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/toystarry/daniel.jpg",
      },
    ],
  },
  {
    name: "E.T. Phone Jones",
    members:
      "Lizzie Craig, Anna Stravato, Max Hess, Karen Martinez, Benjamin Kwait-Gonchar",
    img: "./images/oweek/oweek-groups/et/et.jpg",
    profiles: [
      {
        name: "LIZZIE C",
        email: "ejc16@rice.edu",
        major: "Art History and Biosciences",
        collegetag: "./college-tags/duncan_tag.png",
        img: "./images/oweek/oweek-groups/et/lizzie.jpg",
      },
      {
        name: "ANNA S",
        email: "ams53@rice.edu",
        major: "English and French",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/et/anna.jpg",
      },
      {
        name: "MAX H",
        email: "mh212@rice.edu",
        major: "Philosophy",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/et/max.jpg",
      },
      {
        name: "KAREN M",
        email: "km102@rice.edu",
        major: "Psychology",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/et/karen.jpg",
      },
      {
        name: "BENJAMIN K.G.",
        email: "bk62@rice.edu",
        major: "Physics and Earth, Enviornmental, and Planetary Sciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/et/bkg.jpg",
      },
    ],
  },
  {
    name: "Wizards of Waverly Space",
    members: "Toby Slatken, Sergio Rojas, Nilda Izquierdo, Komal Talloo",
    img: "./images/oweek/oweek-groups/wizards/wizards.jpg",
    profiles: [
      {
        name: "TOBY S",
        email: "ts112@rice.edu",
        major: "Statistics and Business",
        collegetag: "./college-tags/duncan_tag.png",
        img: "./images/oweek/oweek-groups/wizards/toby.jpg",
      },
      {
        name: "SERGIO R",
        email: "sr111@rice.edu",
        major: "Business and Sports Management",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/wizards/sergio.jpg",
      },
      {
        name: "NILDA I",
        email: "ni7@rice.edu",
        major: "Bioengineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/wizards/nilda.jpg",
      },
      {
        name: "KOMAL T",
        email: "kst8@rice.edu",
        major: "Bioengineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/wizards/komal.jpg",
      },
    ],
  },
  {
    name: "Ru Paul's Drag Space: All Stars",
    members: "Nat Pujet, Anael Roig-Gicguel, Sophia Straus, Anthony Valente",
    img: "./images/oweek/oweek-groups/rupaul/rupaul.jpg",
    profiles: [
      {
        name: "NAT P",
        email: "np60@rice.edu",
        major: "Earth, Enviornmental, and Planetary Sciences",
        collegetag: "./college-tags/dunacn_tag.png",
        img: "./images/oweek/oweek-groups/rupaul/nat.jpg",
      },
      {
        name: "ANAEL R.G.",
        email: "ar208@rice.edu",
        major: "Bioengineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/rupaul/anael.jpg",
      },
      {
        name: "SOPHIA S",
        email: "ss531@rice.edu",
        major: "Astrophysics",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/rupaul/sophia.jpg",
      },
      {
        name: "ANTHONY R",
        email: "amv15@rice.edu",
        major: "Neuroscience",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/oweek/oweek-groups/rupaul/anthony.jpg",
      },
    ],
  },
];

export const PAAs = [
  {
    name: "JACKSON O'BRIAN",
    email: "jo60@rice.edu",
    major: "Mechanical Engineering",
    img: "./images/oweek/paas/jackson.png",
  },
  {
    name: "COLEMAN O'BRIAN",
    email: "co63@rice.edu",
    major: "Mechanical Engineering",
    img: "./images/oweek/paas/coleman.jpg",
  },
  {
    name: "SHIVANI PATEL",
    email: "sjp11@rice.edu",
    major: "Biology and Neuroscience",
    img: "./images/oweek/paas/shivani_p.png",
  },
  {
    name: "MAYA IYENGAR",
    email: "mi28@rice.edu",
    major: "Sports Management and SOPA",
    collegetag: "./college-tags/jones_tag.png",
    img: "./images/oweek/paas/maya_i.png",
  },
];

export const Gophers = [
  {
    name: "TBD",
    email: "--",
    major: "--",
    collegetag: "./college-tags/jones_tag.png",
    img: "./images/jones_logo_l.jpeg",
  },
];
