export const Associates = [
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Executive Assistant To The VP Of Enrollment",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "Go to Associate's Night (a reception and dinner extravaganza held each semester on behalf of the North Servery Chef). Take their classes. Keep in touch with your O-Week Associates. Facebook friend them if you must. If you're looking for some good conversation and some cool adults, just introduce yourself. They're really eager to meet you, and they have plenty of stories and memories from their own Jones and Rice experiences. And just think: you might someday become an Associate too!",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    },
    {
        "name": "Jones College",
        "img": "images/inferno_goat.png",
        "fullimg": "images/aaron_pathak.jpg",
        "email": "hch7@rice.edu",
        "shortdesc": "Mad Scientist",
        "longdesc": "We are mad scientists.",
        "imgobjpos": '-10px 0px',
        "imgmaxsize": '110%',
        "fullimgobjpos": '-90px 0px',
        "fullimgmaxsize": '100%'
    }
]