export const CoordLetter = {
  text: "We are Harry, Sarah, and Sofia (otherwise known as the Casinoords), and we're coordinating your O-Week! We were elected at the end of the Fall 2021 semester by Jones College and have been working since January to make sure O-Week 2022 is as fun, informative, and fulfilling as possible. We are so excited to welcome you into Jones, a place that has meant so much to the three of us, and we can assure you with 110% certainty that your advisors and all the other Jonesians can't wait to meet you either. This is the start of a great new chapter in your life, and our goal for O-Week is to familiarize you with all the resources you have available to you (including alumni, associates, advisors, and offices on campus) so you can make something incredible out of your Rice experience. \n\nRice Orientation Week, more commonly known as O-Week, is very different from normal university orientations. It's a full week of events that basically fit into three categories: those that help you plan your classes, those that describe the opportunities and resources you have here at Rice and beyond, and those that make you feel at home in Houston, on campus, and especially at Jones. \n\nNo need to worry about planning anything beforehand. We'll walk you through everything you need to know and do during the week! It'll be a lot to take in, but trust us, it's going to be a great time. \n\n The first people you'll meet when you get here will be your O-Week group: four upperclassman advisors and about eight other new students. (You can look up your advisors in this book.) This is your new little family. These are the people who will guide you, support you, and be there for you even after O-Week itself ends. Together, you'll learn many fundamental truths: why Jones is the winningest college, why Beer Bike is the best sport ever, and what makes Jones a family. As you come to rely on your new family here at Jones, we will teach you to embrace our defining characteristic of winning. This doesn't necessarily mean that Jones always comes in first place, nor do we expect you to. It describes an attitude and a philosophy of life that Jonesians subscribe to. When we chant “Jones Wins Again,” it means that regardless of the outcome of an event, we all get to be winners because we get to head back to Jones. It is this strong sense of pride and fellowship that makes us feel lucky to call Jones our home because when we're together, there's no doubt that all we do is win. \n\nWhile at Rice, you'll quickly learn to love (or put up with) our obsession with themes and punny names. So why CasinO-Week? CasinO-Week is built around two main values: courage and support. We remember when we decided to come to Rice, and it was daunting. Your matriculating class comes from all places, backgrounds, identities, lifestyles, and traditions, and as excited as you are to attend such an amazing university, putting yourselves in this new environment is intimidating. But even in a totally new place with totally new people, we don't want you to shy away from taking risks. Each and every one of the special experiences we have had here has come about because a risk we took paid off. Whether it's attending a new club meeting (or starting your own!), taking a class you're unsure about (or teaching your own!), or joining an intramural sports team (or forming your own!), we want new students to come away from O-Week with the courage to make the most of their Rice experience. And at the end of the day, the most important lesson is that Jones will be there to support you. Your fellow Jonesians know that not every gamble pays off, and we'll be there for the highs and the lows. \n\nBy the time you read this, we will already be in Houston planning O-Week. If you have any concerns, requests for advice, packing questions, weather forecasting needs, or movie recommendations, please don't hesitate to reach out—that's why we're here. \n\nSee you soon!",
  coordInfo: [
    {
      name: "Delaney Miller",
      phone: "delaney.e.miller@rice.edu",
      img: "./images/advisors/delaneymiller.png",
    },
    {
      name: "Ithzel Rubio",
      phone: "ithzel.rubio@rice.edu",
      img: "./images/advisors/ithzelrubio.png",
    },
    {
      name: "Dheerj Jasuja",
      phone: "dheerj.jasuja@rice.edu",
      img: "./images/advisors/dheerj.png",
    },
  ],
  email: "jonesoweek@rice.edu ",
};

export const CoordBios = [
  {
    name: "DELANEY MILLER",
    bio: "Delaney is a junior from Los Angeles, CA studying Computer Science, Cognitive Science, and minoring in Spanish. In her free time, she loves cooking, exploring new places, or anything active, especially running and biking for the Jones Bike Team!",
    img: "./images/advisors/delaneymiller.png",
  },
  {
    name: "ITHZEL RUBIO",
    bio: "Ithzel is a rising junior from Waco, TX studying Sociology, as well as minoring in Business and PLST. In her free time, she loves watching old 2000s cartoons, exploring Houston, and playing for the Marching Owl Band!",
    img: "./images/advisors/ithzelrubio.png",
  },
  {
    name: "DHEERJ JASUJA",
    bio: "Dheerj is a rising junior from San Jose, CA, majoring in Neuroscience and minoring in Sociology. Outside of class, he enjoys listening to music, playing chess, and practicing soccer. He is excited to meet all of the new students and looks forward to O-Week!",
    img: "./images/advisors/dheerj.png",
  },
];

export const OWeekGroups = [
  {
    name: "Sun Direction: Moonlight Memories",
    members:
      "Asha Zinke, Brandon Nunez, Samy Martinez, Varsha Chandramouli, Zach Donovan",
    img: "./images/o-week-groups/sundirection/sundirection.jpeg",
    profiles: [
      {
        name: "ASHA Z",
        email: "aasha.g.zinke@rice.edu",
        major: "Material Science & Nano Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/sundirection/ashaz.jpeg",
      },
      {
        name: "BRANDON N",
        email: "brandon.nunez@rice.edu",
        major: "Natural Sciences Division",
        collegetag: "./college-tags/mcmurtry_tag.png",
        img: "./images/o-week-groups/sundirection/brandonn.jpeg",
      },
      {
        name: "SAMY M",
        email: "sm201@rice.edu",
        major: "Engineering Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/sundirection/samym.png",
      },
      {
        name: "VARSHA C",
        email: "varsha.k.chandramouli@rice.edu",
        major: "Sports Medicine & Exercise Phy",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/sundirection/varshac.jpeg",
      },
      {
        name: "ZACK D",
        email: "zack.donovan@rice.edu",
        major: "Natural Sciences Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/sundirection/zackd.jpeg",
      },
    ],
  },
  {
    name: "Glochella",
    members: "Piper Winn, Raleigh Bellard, Alex Xu, Skye Fredericks, Zach Pool",
    img: "./images/o-week-groups/glochella/glochella.JPG",
    profiles: [
      {
        name: "PIPER W",
        email: "piper.j.winn@rice.edu",
        major: "Sports Medicine & Exercise Phy",
        collegetag: "./college-tags/baker_tag.png",
        img: "./images/o-week-groups/glochella/piperw.jpg",
      },
      {
        name: "RALEIGH B",
        email: "raleigh.s.bellard@rice.edu",
        major: "Biosciences",
        collegetag: "./college-tags/baker_tag.png",
        img: "./images/o-week-groups/glochella/raleighb.JPG",
      },
      {
        name: "ALEX X",
        email: "alexandra.xu@rice.edu",
        major: "Social Sciences Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glochella/alexx.JPG",
      },
      {
        name: "SKYE F",
        email: "skye.k.fredericks@rice.edu",
        major: "Social Policy Analysis Anthropology",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glochella/skyef.JPG",
      },
      {
        name: "ZACH P",
        email: "zach.pool@rice.edu",
        major: "Visual and Dramatic Arts",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glochella/zachp.JPG",
      },
    ],
  },
  {
    name: "H2GLO: Just Add WATTer",
    members:
      "Gautam Chaudhry, Joel Villarino, Ryan MacMurray, Wed Timraz, Mahliya Dolan",
    img: "./images/o-week-groups/h2glow/h2glow.png",
    profiles: [
      {
        name: "GAUTAM C",
        email: "gautam.chaudhry@rice.edu",
        major: "Chemistry",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/h2glow/gautamc.JPG",
      },
      {
        name: "JOEL V",
        email: "joel.a.villarino@rice.edu",
        major: "Computer Science",
        collegetag: "./college-tags/sid_tag.png",
        img: "./images/o-week-groups/h2glow/joelv.JPG",
      },
      {
        name: "RYAN M",
        email: "rrm@rice.edu",
        major: "Chemistry",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/h2glow/ryanm.JPG",
      },
      {
        name: "WED T",
        email: "wed.h.timraz@rice.edu",
        major: "History",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/h2glow/wedt.JPG",
      },
      {
        name: "MAHLIYA D",
        email: "mahliya.m.dolan@rice.edu",
        major: "Engineering Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/h2glow/mahliyad.JPG",
      },
    ],
  },
  {
    name: "AvaSTAR: The Last FLAREbender",
    members: "Gospel Ibe, Gretchen Schulke, Katie Maurano, Megan Enriquez",
    img: "./images/o-week-groups/avastar/avastar.JPG",
    profiles: [
      {
        name: "GOSPEL I",
        email: "gii1@rice.edu",
        major: "Sports Medicine & Exercise Phy",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/avastar/gospeli.JPG",
      },
      {
        name: "GRETCHEN S",
        email: "gretchen.n.schulke@rice.edu",
        major: "Mechanical Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/avastar/gretchens.JPG",
      },
      {
        name: "KATIE M",
        email: "km78@rice.edu",
        major: "Psychology & Visual and Dramatic Arts",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/avastar/katiem.JPG",
      },
      {
        name: "MEGAN E",
        email: "megan.enriquez@rice.edu",
        major: "Mechanical Engineering",
        collegetag: "./college-tags/brown_tag.png",
        img: "./images/o-week-groups/avastar/megane.JPG",
      },
    ],
  },
  {
    name: "Hannah GLOtana",
    members: "Edelawit Negash, Ellery Underhill, James Cheng, Jesus Adame",
    img: "./images/o-week-groups/hannahglotana/hannahglotana.jpeg",
    profiles: [
      {
        name: "EDELAWIT N",
        email: "edelawit@rice.edu",
        major: "Economics Business",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/hannahglotana/edelawitn.jpeg",
      },
      {
        name: "ELLERY U",
        email: "ellery.v.underhill@rice.edu",
        major: "Natural Sciences Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/hannahglotana/elleryu.jpeg",
      },
      {
        name: "JAMES C",
        email: "james.d.cheng@rice.edu",
        major: "Biosciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/hannahglotana/jamesc.jpeg",
      },
      {
        name: "JESUS A",
        email: "jesus.adame@rice.edu",
        major: "Social Sciences Division",
        collegetag: "./college-tags/baker_tag.png",
        img: "./images/o-week-groups/hannahglotana/jesusa.jpeg",
      },
    ],
  },
  {
    name: "Evergleam Everglare All At Once",
    members: "Ben Smiley, Dumari De Leon, Grace Stewart, Saumya Jhaveri",
    img: "./images/o-week-groups/evergleam/evergleameverywhere.JPG",
    profiles: [
      {
        name: "BEN S",
        email: "bms8@rice.edu",
        major: "Civil Engineering",
        collegetag: "./college-tags/wiess_tag.png",
        img: "./images/o-week-groups/evergleam/bens.png",
      },
      {
        name: "DUMARI D",
        email: "dmd11@rice.edu",
        major: "Environmental Science",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/evergleam/dumarid.JPG",
      },
      {
        name: "GRACE S",
        email: "grace.e.stewart@rice.edu",
        major: "History",
        collegetag: "./college-tags/hanszen_tag.png",
        img: "./images/o-week-groups/evergleam/graces.JPG",
      },
      {
        name: "SAUMYA J",
        email: "saj6@rice.edu",
        major: "Managerial Econ & Org Sci",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/evergleam/saumyaj.JPG",
      },
    ],
  },
  {
    name: "Glow White and the 7 Dwarfs",
    members: "Daniel Li, Dylan Council, Komal Talloo, Samantha Ogundare",
    img: "./images/o-week-groups/glowwhite/glowwhite.JPG",
    profiles: [
      {
        name: "DANIEL L",
        email: "dyl2@rice.edu",
        major: "Cognitive Sciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glowwhite/daniell.jpg",
      },
      {
        name: "DYLAN C",
        email: "dylan.h.council@rice.edu",
        major: "Social Sciences Division",
        collegetag: "./college-tags/sid_tag.png",
        img: "./images/o-week-groups/glowwhite/dylanc.JPG",
      },
      {
        name: "KOMAL T",
        email: "kst8@rice.edu",
        major: "Social Sciences Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glowwhite/komalt.JPG",
      },
      {
        name: "SAM O",
        email: "samantha.ogundare@rice.edu",
        major: "Engineering Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glowwhite/samanthao.JPG",
      },
    ],
  },
  {
    name: "Mike Watt-zowski: Monsters, Blink.",
    members: "Catherine Cook, Korinna Ruiz, Mina Schepmann, Zarek lu",
    img: "./images/o-week-groups/mikewatt/mikewatt.png",
    profiles: [
      {
        name: "CATHERINE C",
        email: "catherine.cook@rice.edu",
        major: "Neuroscience & Health Sciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/mikewatt/catherinec.jpeg",
      },
      {
        name: "KORINNA R",
        email: "kar13@rice.edu",
        major: "Biosciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/mikewatt/korinnar.jpeg",
      },
      {
        name: "MINA S",
        email: "mina.schepmann@rice.edu",
        major: "Mechanical Engineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/mikewatt/minas.jpeg",
      },
      {
        name: "ZAREK L",
        email: "zarek.f.lu@rice.edu",
        major: "Computer Science",
        collegetag: "./college-tags/hanszen_tag.png",
        img: "./images/o-week-groups/mikewatt/zarekl.jpeg",
      },
    ],
  },
  {
    name: "My Neighbor GLOtoro",
    members: "Alex Breazeale, Doug Calvillo, Shreya Majeti",
    img: "./images/o-week-groups/glotoro/glotoro.JPG",
    profiles: [
      {
        name: "ALEX B",
        email: "alex.w.breazeale@rice.edu",
        major: "Natural Sciences Division",
        collegetag: "./college-tags/wiess_tag.png",
        img: "./images/o-week-groups/glotoro/alexb.jpeg",
      },
      {
        name: "ARYA M",
        email: "-",
        major: "-",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glotoro/aryam.JPG",
      },
      {
        name: "DOUG C",
        email: "doug.calvillo@rice.edu",
        major: "Neuroscience, Health Sciences, & Psychology",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glotoro/dougc.JPG",
      },
      {
        name: "SHREYA M",
        email: "shreya.majeti@rice.edu",
        major: "Bioengineering",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/glotoro/shreyam.JPG",
      },
    ],
  },
  {
    name: "Flarey Potter and the GobLIT of Fire",
    members: "Savan Patel, Samuel Barton, Nilda Jarero, Leela Sydow",
    img: "./images/o-week-groups/flareypotter/flareypotter.JPG",
    profiles: [
      {
        name: "SAMUEL B",
        email: "spb3@rice.edu",
        major: "Astrophysics",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/flareypotter/samuelb.JPG",
      },
      {
        name: "SAVAN P",
        email: "savan.a.patel@rice.edu",
        major: "Business Division",
        collegetag: "./college-tags/wiess_tag.png",
        img: "./images/o-week-groups/flareypotter/savanp.JPG",
      },
      {
        name: "NILDA J",
        email: "nilda.m.jarero@rice.edu",
        major: "Computer Science & Cognitive Sciences",
        collegetag: "./college-tags/duncan_tag.png",
        img: "./images/o-week-groups/flareypotter/nildaj.JPG",
      },
      {
        name: "LEELA S",
        email: "leela.p.sydow@rice.edu",
        major: "Humanities Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/flareypotter/leelas.JPG",
      },
    ],
  },
  {
    name: "Vincent van Glow: The Starry Night",
    members:
      "Abigail Jablon, Audrey Nguyen, Caden Acosta, Jorge Arnez Gonzales, Theo Schweizer",
    img: "./images/o-week-groups/vvglow/vvglow.JPG",
    profiles: [
      {
        name: "ABIGAIL J",
        email: "abigail.jablon@rice.edu",
        major: "Architecture Divisions",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/vvglow/abigailj.JPG",
      },
      {
        name: "AUDREY N",
        email: "audrey.t.nguyen@rice.edu",
        major: "Biosciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/vvglow/audreyn.JPG",
      },
      {
        name: "CADEN A",
        email: "caden.acosta@rice.edu",
        major: "Engineering Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/vvglow/cadena.JPG",
      },
      {
        name: "JORGE A",
        email: "jorge.l.arnez.gonzales@rice.edu",
        major: "Biosciences",
        collegetag: "./college-tags/brown_tag.png",
        img: "./images/o-week-groups/vvglow/jorgea.png",
      },
      {
        name: "THEO S",
        email: "theo.schweizer@rice.edu",
        major: "Computer Science",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/vvglow/theos.JPG",
      },
    ],
  },
  {
    name: "Pokémon Glo: Jones, I choose you!",
    members: "Skyler Zinker, Ryan Hartgerink, Anthony Valente, Adi Peddi",
    img: "./images/o-week-groups/pokemonglow/pokemonglow.JPG",
    profiles: [
      {
        name: "ADI P",
        email: "adi.peddi@rice.edu",
        major: "Biosciences",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/pokemonglow/adip.jpeg",
      },
      {
        name: "ANTHONY V",
        email: "anthony.m.valente@rice.edu",
        major: "Natural Sciences Division",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/pokemonglow/anthonyv.jpeg",
      },
      {
        name: "RYAN H",
        email: "ryan.e.hartgerink@rice.edu",
        major: "Neuroscience",
        collegetag: "./college-tags/jones_tag.png",
        img: "./images/o-week-groups/pokemonglow/ryanh.jpeg",
      },
      {
        name: "SKYLER Z",
        email: "skyler.c.zinker@rice.edu",
        major: "Social Sciences Division",
        collegetag: "./college-tags/wiess_tag.png",
        img: "./images/o-week-groups/pokemonglow/skylerz.JPG",
      },
    ],
  },
];

export const PAAs = [
  {
    name: "ARRYANA LYON",
    email: "arryana.lyon@rice.edu",
    major: "Social Sciences Division",
    img: "./images/paas/ArryanaLyon.jpg",
  },
  {
    name: "EDUARDO RUIZ",
    email: "eduardo.ruiz@rice.edu",
    major: "Biosciences",
    img: "./images/advisors/EduardoRuiz.png",
  },
  {
    name: "MAYA HOFFMAN",
    email: "maya.hoffman@rice.edu",
    major: "Health Sciences",
    img: "./images/advisors/MayaHoffman.png",
  },
  {
    name: "RIJA NAQVI",
    email: "rija.h.naqvi@rice.edu",
    major: "Biosciences",
    collegetag: "./college-tags/jones_tag.png",
    img: "./images/advisors/RijaNaqvi.jpg",
  },
];

export const Gophers = [
  {
    name: "SAMY M",
    email: "sm201@rice.edu",
    major: "Engineering Division",
    collegetag: "./college-tags/jones_tag.png",
    img: "./images/o-week-groups/sundirection/samym.jpeg",
  },
  {
    name: "MAHLIYA D",
    email: "mahliya.m.dolan@rice.edu",
    major: "Engineering Division",
    collegetag: "./college-tags/jones_tag.png",
    img: "./images/o-week-groups/h2glow/mahliyad.JPG",
  },
];
